baseURL = 'https://kbose.me/'
languageCode = 'en-us'
title = "K Bose's Blog"
theme = "hugo-theme-stack"

[params.sidebar]
compact = false
emoji = "🖖"
subtitle = "Research Scientist | PGIMER"


[menu]
    [[menu.social]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/k-bose"
        params = { icon = "brand-github" }

    [[menu.social]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/0xkbose"
        params = { icon = "brand-twitter" }

    [[menu.social]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://linkedin.com/in/k-bose"
        params = { icon = "brand-linkedin" }

[params.sidebar.avatar]
enabled = true
src = "img/avatar.webp"
local = true
